name = "ahmed-finance-exam"
main = "src/worker.js"
compatibility_date = "2026-09-14"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ahmed-finance-exam-db"
database_id = "046cfb7a-be02-4d31-b550-03d4260c5005"
migrations_dir = "migrations"

[vars]
SESSION_DAYS = "7"
